baseURL = 'https://freedie.org/'
languageCode = 'en-us'
title = 'Freedie | Pentesting Lab Writeups'
theme = 'hugo-theme-hello-friend-ng'

[[params.social]]
  name = "https://feathericons.com/?query=linked"
  url = "https://www.linkedin.com/in/freedie/"

[[menu.main]]
  identifier = "writeups"
  name = "Writeups"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20
