baseURL = 'https://freedie.org/'
languageCode = 'en-us'
title = 'Freedie | Pentesting Lab Writeups'
theme = 'hugo-theme-hello-friend-ng'

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/freedie/"

[[params.social]]
  name = "hackthebox"
  url = "https://app.hackthebox.com/users/1101181"

[[params.social]]
  name = "medium"
  url = "https://medium.com/@freedietse"

[[params.social]]
  name = "tryhackme"
  url = "https://tryhackme.com/p/Freedie"

[[params.social]]
  name = "email"
  url = "mailto:fhftse@uwaterloo.ca"

[[params.social]]
  name = "discord"
  url = "hiroto"

[[menu.main]]
  identifier = "HTB writeups"
  name = "HTB Writeups"
  url = "/Hack The Box/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20
