baseURL = 'https://freedie.org/'
languageCode = 'en-us'
title = 'Freedie | Pentesting Lab Writeups'
theme = 'hugo-theme-hello-friend-ng'

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20
